export const items = [
  {
    name: "Armored Wall",
    image: "/images/wall4.png",
    destructionOptions: {
      c4: 8,
      bullets: 799,
      rockets: 15,
      satchel: 46,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 30,
      rockets: 14,
      satchel: 0,
    },
  },
  {
    name: "Metal Wall",
    image: "/images/wall3.png",
    destructionOptions: {
      c4: 4,
      bullets: 400,
      rockets: 8,
      satchel: 23,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 15,
      rockets: 7,
      satchel: 0,
    },
  },
  {
    name: "Stone Wall",
    image: "/images/wall2.png",
    destructionOptions: {
      c4: 2,
      bullets: 185,
      rockets: 4,
      satchel: 10,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 35,
      rockets: 3,
      satchel: 0,
    },
  },
  {
    name: "Wooden Wall",
    image: "/images/wall1.png",
    destructionOptions: {
      c4: 1,
      bullets: 49,
      rockets: 2,
      satchel: 3,
    },
    category: "Walls",
  },
  {
    name: "Strengthened window",
    image: "/images/wall.window.glass.reinforced.png",
    destructionOptions: {
      c4: 2,
      bullets: 140,
      rockets: 3,
      satchel: 9,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 30,
      rockets: 2,
      satchel: 0,
    },
  },
  {
    name: "Reinforced window",
    image: "/images/wall.window.bars.toptier.png",
    destructionOptions: {
      c4: 2,
      bullets: 200,
      rockets: 4,
      satchel: 12,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 35,
      rockets: 3,
      satchel: 0,
    },
  },
  {
    name: "Chainlink Fence",
    image: "/images/wall.frame.fence.png",
    destructionOptions: {
      c4: 1,
      bullets: 20,
      rockets: 1,
      satchel: 2,
    },
    category: "Walls",
    bestOption: {
      c4: 0,
      bullets: 20,
      rockets: 0,
      satchel: 0,
    },
  },
  {
    name: "Metal Window Bars",
    image: "/images/wall.window.bars.metal.png",
    destructionOptions: {
      c4: 2,
      bullets: 200,
      rockets: 4,
      satchel: 12,
    },
    category: "Walls",
  },
  {
    name: "Metal Vertical Embrasure",
    image: "/images/shutter.metal.embrasure.b.png",
    destructionOptions: {
      c4: 2,
      bullets: 173,
      rockets: 4,
      satchel: 13,
    },
    category: "Walls",
  },
  {
    name: "Metal Horizontal Embrasure",
    image: "/images/shutter.metal.embrasure.a.png",
    destructionOptions: {
      c4: 2,
      bullets: 173,
      rockets: 4,
      satchel: 13,
    },
    category: "Walls",
  },
  {
    name: "Prison Cell Wall",
    image: "/images/wall.frame.cell.png",
    destructionOptions: {
      c4: 1,
      bullets: 75,
      rockets: 2,
      satchel: 5,
    },
    category: "Walls",
    bestOption: {
      c4: 1,
      bullets: 0,
      rockets: 0,
      satchel: 0,
    },
  },
  {
    name: "Chainlink Fence Gate",
    image: "/images/wall.frame.fence.gate.png",
    destructionOptions: {
      c4: 1,
      bullets: 15,
      rockets: 3,
      satchel: 1,
    },
    category: "Doors",
    bestOption: {
      c4: 0,
      bullets: 15,
      rockets: 0,
      satchel: 0,
    },
  },
  {
    name: "Prison Cell Gate",
    image: "/images/wall.frame.cell.gate.png",
    destructionOptions: {
      c4: 1,
      bullets: 75,
      rockets: 2,
      satchel: 5,
    },
    category: "Doors",
    bestOption: {
      c4: 1,
      bullets: 0,
      rockets: 0,
      satchel: 0,
    },
  },
  {
    name: "Sheet Metal Door",
    image: "/images/door.hinged.metal.png",
    destructionOptions: {
      c4: 1,
      bullets: 63,
      rockets: 2,
      satchel: 4,
    },
    category: "Doors",
    bestOption: {
      c4: 0,
      bullets: 8,
      rockets: 1,
      satchel: 0,
    },
  },
  {
    name: "Armored Door",
    image: "/images/door.hinged.toptier.png",
    destructionOptions: {
      c4: 3,
      bullets: 250,
      rockets: 5,
      satchel: 15,
    },
    category: "Doors",
  },
  {
    name: "Wooden Door",
    image: "/images/door.hinged.wood.png",
    destructionOptions: {
      c4: 1,
      bullets: 19,
      rockets: 1,
      satchel: 2,
    },
    category: "Doors",
    bestOption: {
      c4: 0,
      bullets: 30,
      rockets: 4,
      satchel: 0,
    },
  },
  {
    name: "Garage Door",
    image: "/images/wall.frame.garagedoor.png",
    destructionOptions: {
      c4: 2,
      bullets: 150,
      rockets: 3,
      satchel: 9,
    },
    category: "Doors",
    bestOption: {
      c4: 0,
      bullets: 0,
      rockets: 3,
      satchel: 0,
    },
  },
  {
    name: "Ladder Hatch",
    image: "/images/floor.ladder.hatch.png",
    destructionOptions: {
      c4: 1,
      bullets: 63,
      rockets: 2,
      satchel: 4,
    },
    category: "Doors",
  },
  {
    name: "Ladder Hatch Triangle",
    image: "/images/floor.triangle.ladder.hatch.png",
    destructionOptions: {
      c4: 1,
      bullets: 63,
      rockets: 2,
      satchel: 4,
    },
    category: "Doors",
  },
  {
    name: "Metal Shop Front",
    image: "/images/wall.frame.shopfront.metal.png",
    destructionOptions: {
      c4: 3,
      bullets: 300,
      rockets: 6,
      satchel: 18,
    },
    category: "Doors",
  },
  {
    name: "External Wooden Wall",
    image: "/images/wall.external.high.png",
    destructionOptions: {
      c4: 2,
      bullets: 98,
      rockets: 3,
      satchel: 6,
    },
    category: "External Walls",
  },
  {
    name: "External Stone Wall",
    image: "/images/wall.external.high.stone.png",
    destructionOptions: {
      c4: 2,
      bullets: 185,
      rockets: 4,
      satchel: 10,
    },
    category: "External Walls",
  },
  {
    name: "Auto Turret",
    image: "/images/autoturret.png",
    destructionOptions: {
      c4: 1,
      bullets: 112,
      rockets: 4,
      satchel: 2,
    },
    category: "Defenses",
  },
  {
    name: "Shotgun Trap",
    image: "/images/guntrap.png",
    destructionOptions: {
      c4: 1,
      bullets: 34,
      rockets: 2,
      satchel: 1,
    },
    category: "Defenses",
  },
  {
    name: "Metal Barricade",
    image: "/images/barricade.metal.png",
    destructionOptions: {
      c4: 1,
      bullets: 111,
      rockets: 3,
      satchel: 4,
    },
    category: "Defenses",
  },
  {
    name: "Flame Turret",
    image: "/images/flameturret.png",
    destructionOptions: {
      c4: 1,
      bullets: 34,
      rockets: 2,
      satchel: 1,
    },
    category: "Defenses",
  },
  {
    name: "SAM Site",
    image: "/images/samsite.png",
    destructionOptions: {
      c4: 1,
      bullets: 200,
      rockets: 4,
      satchel: 2,
    },
    category: "Defenses",
  },
  {
    name: "Workbench lvl 1",
    image: "/images/workbench1.png",
    destructionOptions: {
      c4: 1,
      bullets: 56,
      rockets: 2,
      satchel: 1,
    },
    category: "Furniture",
  },
  {
    name: "Workbench lvl 2",
    image: "/images/workbench2.png",
    destructionOptions: {
      c4: 1,
      bullets: 173,
      rockets: 4,
      satchel: 7,
    },
    category: "Furniture",
  },
  {
    name: "Workbench lvl 3",
    image: "/images/workbench3.png",
    destructionOptions: {
      c4: 2,
      bullets: 259,
      rockets: 6,
      satchel: 10,
    },
    category: "Furniture",
  },
  {
    name: "Vending Machine",
    image: "/images/vending.machine.png",
    destructionOptions: {
      c4: 3,
      bullets: 499,
      rockets: 10,
      satchel: 15,
    },
    category: "Furniture",
  },
];
